#### 1. Scenario: A company wants to analyze the sales performance of its products in different regions. They have collected the following data:
   Region A: [10, 15, 12, 8, 14]
   Region B: [18, 20, 16, 22, 25]
   Calculate the mean sales for each region.


In [6]:
import numpy as np
region1=[10,15,12,8,14]
region2=[18,20,16,22,25]
r1mean=np.mean(region1)
r2mean=np.mean(region2)
print(r1mean)
print(r2mean)

11.8
20.2


#### 2. Scenario: A survey is conducted to measure customer satisfaction on a scale of 1 to 5. The data collected is as follows:
   [4, 5, 2, 3, 5, 4, 3, 2, 4, 5]
   Calculate the mode of the survey responses.


In [7]:
import statistics as st
r1=[4,5,2,3,5,4,3,2,4]
print(st.mode(r1))

4


#### 3. Scenario: A company wants to compare the salaries of two departments. The salary data for Department A and Department B are as follows:
   Department A: [5000, 6000, 5500, 7000]
   Department B: [4500, 5500, 5800, 6000, 5200]
   Calculate the median salary for each department.


In [8]:
depta = [5000, 6000, 5500, 7000] 
deptb = [4500, 5500, 5800, 6000, 5200]
print(np.median(depta))
print(np.median(deptb))

5750.0
5500.0


#### 4. Scenario: A data analyst wants to determine the variability in the daily stock prices of a company. The data collected is as follows:
   [25.5, 24.8, 26.1, 25.3, 24.9]
   Calculate the range of the stock prices.


In [9]:
c1 = [25.5, 24.8, 26.1, 25.3, 24.9]
print(max(c1)-min(c1))

1.3000000000000007


#### 5. Scenario: A study is conducted to compare the performance of two different teaching methods. The test scores of the students in each group are as follows:
   Group A: [85, 90, 92, 88, 91]
   Group B: [82, 88, 90, 86, 87]
   Perform a t-test to determine if there is a significant difference in the mean scores between the two groups.


In [10]:
from scipy.stats import stats
g1 = [85, 90, 92, 88, 91]
g2 =  [82, 88, 90, 86, 87] 

res = stats.ttest_ind(g1,g2)

In [11]:
print(res)

Ttest_indResult(statistic=1.4312528946642733, pvalue=0.19023970239078333)


#### 6. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
   Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
   Sales (in thousands): [25, 30, 28, 20, 26]
   Calculate the correlation coefficient between advertising expenditure and sales.


In [12]:
s1 = [10, 15, 12, 8, 14] 
s2 = [25, 30, 28, 20, 26] 

print(np.corrcoef(s1,s2))

[[1.         0.87575114]
 [0.87575114 1.        ]]


#### 7. Scenario: A survey is conducted to measure the heights of a group of people. The data collected is as follows:
   [160, 170, 165, 155, 175, 180, 170]
   Calculate the standard deviation of the heights.


In [13]:
h1 = [160, 170, 165, 155, 175, 180, 170] 
print(np.std(h1))

7.953949089757174


#### 8. Scenario: A company wants to analyze the relationship between employee tenure and job satisfaction. The data collected is as follows:
   Employee Tenure (in years): [2, 3, 5, 4, 6, 2, 4]
   Job Satisfaction (on a scale of 1 to 10): [7, 8, 6, 9, 5, 7, 6]
   Perform a linear regression analysis to predict job satisfaction based on employee tenure.


In [15]:
from sklearn.linear_model import LinearRegression
emp_y = np.array( [2, 3, 5, 4, 6, 2, 4] )
emp_y = emp_y.reshape(-1,1)
j_sat = np.array( [7, 8, 6, 9, 5, 7, 6])
j_sat = j_sat.reshape(-1,1)
model = LinearRegression()
model.fit(emp_y,j_sat)

LinearRegression()

In [16]:
model.predict([[2]])

array([[7.65957447]])

#### 10. Scenario: A company wants to analyze customer feedback ratings on a scale of 1 to 10. The data collected is

 as follows:
    [8, 9, 7, 6, 8, 10, 9, 8, 7, 8]
    Calculate the 75th percentile of the feedback ratings


In [20]:
s1 = [8, 9, 7, 6, 8, 10, 9, 8, 7, 8] 
print(np.percentile(s1,0.75))

6.0675


#### 11. Scenario: A quality control department wants to test the weight consistency of a product. The weights of a sample of products are as follows:
    [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]
    Perform a hypothesis test to determine if the mean weight differs significantly from 10 grams.


In [21]:
w1 = [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]
print(stats.ttest_1samp(w1,10))

Ttest_1sampResult(statistic=1.5126584522688367, pvalue=0.19077595151110102)


#### 12. Scenario: A company wants to analyze the click-through rates of two different website designs. The number of clicks for each design is as follows:
    Design A: [100, 120, 110, 90, 95]
    Design B: [80, 85, 90, 95, 100]
    Perform a chi-square test to determine if there is a significant difference in the click-through rates between the two designs.


In [23]:
designa = [100, 120, 110, 90, 95]
designb = [80, 85, 90, 95, 100]

res = np.array([designa,designb])

print(stats.chisquare(res,axis=None))


Power_divergenceResult(statistic=12.979274611398964, pvalue=0.16354630879777343)


#### 13. Scenario: A survey is conducted to measure customer satisfaction with a product on a scale of 1 to 10. The data collected is as follows:
    [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]
    Calculate the 95% confidence interval for the population mean satisfaction score.


In [24]:
import numpy as np
import scipy.stats as stats

# Customer satisfaction scores
scores = [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]

# Calculate the sample mean and sample standard deviation
sample_mean = np.mean(scores)
sample_std = np.std(scores, ddof=1)  # ddof=1 for sample standard deviation

# Determine the sample size
n = len(scores)

# Compute the standard error of the mean
standard_error = sample_std / np.sqrt(n)

# Set the desired confidence level
confidence_level = 0.95

# Calculate the critical value
critical_value = stats.t.ppf((1 + confidence_level) / 2, df=n-1)

# Calculate the margin of error
margin_of_error = critical_value * standard_error

# Calculate the lower and upper bounds of the confidence interval
lower_bound = sample_mean - margin_of_error
upper_bound = sample_mean + margin_of_error

# Print the confidence interval
print("Confidence Interval: [{:.3f}, {:.3f}]".format(lower_bound, upper_bound))


Confidence Interval: [7.044, 8.756]


#### 14. Scenario: A company wants to analyze the effect of temperature on product performance. The data collected is as follows:
    Temperature (in degrees Celsius): [20, 22, 23, 19, 21]
    Performance (on a scale of 1 to 10): [8, 7, 9, 6, 8]
    Perform a simple linear regression to predict performance based on temperature.


In [25]:
temp = np.array([20, 22, 23, 19, 21])
perf = np.array([8, 7, 9, 6, 8])
temp = temp.reshape(-1,1)
perf = perf.reshape(-1,1)
model = LinearRegression()
model.fit(temp,perf)

LinearRegression()

In [27]:
model.predict([[20]])

array([[7.1]])

#### 16. Scenario: A company wants to analyze the distribution of customer ages. The data collected is as follows:
    [25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
    Calculate the interquartile range (IQR) of the ages.


In [28]:
from scipy import stats
d1 = [25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
print(stats.iqr(d1,interpolation='midpoint'))

20.0


#### 17. Scenario: A study is conducted to compare the performance of three different machine learning algorithms. The accuracy scores for each algorithm are as follows:
    Algorithm A: [0.85, 0.80, 0.82, 0.87, 0.83]
    Algorithm B: [0.78, 0.82, 0.84, 0.80, 0.79]
    Algorithm C: [0.90, 0.88, 0.89, 0.86, 0.87]
    Perform a Kruskal-Wallis test to determine if there is a significant difference in the median accuracy scores between the algorithms.


In [29]:
data_group1 = [0.85, 0.80, 0.82, 0.87, 0.83]
data_group2 = [0.78, 0.82, 0.84, 0.80, 0.79]
data_group3 = [0.90, 0.88, 0.89, 0.86, 0.87]

result = stats.kruskal(data_group1, data_group2, data_group3)
print(result)
 

KruskalResult(statistic=9.696947935368053, pvalue=0.007840333026249539)


#### 18. Scenario: A company wants to analyze the effect of price on sales. The data collected is as follows:
    Price (in dollars): [10, 15, 12, 8, 14]
    Sales: [100, 80, 90, 110, 95]
    Perform a simple linear regression to predict



In [31]:
price = np.array([10, 15, 12, 8, 14])
price = price.reshape(-1,1)
sales = np.array([100, 80, 90, 110, 95])
sales = sales.reshape(-1,1)

model = LinearRegression()
model.fit(price,sales)

LinearRegression()

In [33]:
model.predict([[10]])

array([[101.31097561]])

#### 19. Scenario: A survey is conducted to measure the satisfaction levels of customers with a new product. The data collected is as follows:
    [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]
    Calculate the standard error of the mean satisfaction score.


In [34]:
d1 = [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]
sd = np.std(d1)
n1 = np.sqrt(len(d1))
print(sd/n1)

0.28982753492378877


#### 20. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
    Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
    Sales (in thousands): [25, 30, 28, 20, 26]
    Perform a multiple regression analysis to predict sales based on advertising expenditure.


In [35]:
ad = np.array([10, 15, 12, 8, 14])
sales= np.array([25, 30, 28, 20, 26])
ad = ad.reshape(-1,1)
sales = sales.reshape(-1,1)
model = LinearRegression()
model.fit(ad,sales)

LinearRegression()

In [37]:
model.predict([[15]])

array([[29.48780488]])